### ISSUE TITLE
Remove completed TODO on the topology of Scott domains

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#263]
@tomdjong: The index of the `DomainTheory` development lists the TODO:

https://github.com/martinescardo/TypeTopology/blob/000d51ae15b9e92d3a2e1bc942a763009f036a53/source/DomainTheory/index.lagda#L173-L178

and says

> If you'd like to work on Item 4, please get in touch with Ayberk Tosun.

This has now been done (in PR #255) so we can remove this TODO (and maybe provide some pointers to the modules in which it has been done).

**Comment by tomdjong** [comment]
Since you implemented this, can you also address this issue and provide the pointers please?

**Comment by ayberkt** [comment]
Sure, I just didn’t want to do this without checking with you first.

Should I simply remove the TODO or should I maybe create a new section on ticked-off TODOs and move it there?

**Comment by tomdjong** [comment]
Just remove the TODO and write a small paragraph how you built on the development and what you showed. It doesn't have to be formatted as a ticking-off of TODOs.
