### ISSUE TITLE
Expressing decidability in terms of semidecidability

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#28]
In `Negation.lagda`, the usual definition of decidability for a type is given:

https://github.com/martinescardo/TypeTopology/blob/f2c26d4be5b7faf36e71ab54d850dd6c3abb71a4/source/Negation.lagda#L42-L43

Would it be possible, in Agda, to express the notion of a _semidecidable_ type so that the decidability of type `A` is (at least) logically equivalent to the conjunction of semidecidability and co-semidecidability of `A`?

**Comment by martinescardo** [comment]
I suggest you look at my paper with @cmknapp https://www.cs.bham.ac.uk/~mhe/papers/partial-elements-and-recursion.pdf and also his PhD thesis https://etheses.bham.ac.uk/id/eprint/8448/ where such questions are addressed in detail.

**Comment by ayberkt** [comment]
> I suggest you look at my paper with @cmknapp https://www.cs.bham.ac.uk/~mhe/papers/partial-elements-and-recursion.pdf and also his PhD thesis https://etheses.bham.ac.uk/id/eprint/8448/ where such questions are addressed in detail.

Thanks!
