### ISSUE TITLE
Give a native coinductive definition of ℕ∞

### ISSUE THREAD

**Issue by martinescardo** [martinescardo/TypeTopology#309]
Here is a TODO that may be interesting.

In TypeTopology we don't allow things that go beyond MLTT extended with Book HoTT, but we do allow experimental things at `Unsafe`.

https://www.cs.bham.ac.uk/~mhe/TypeTopology/Unsafe.index.html

We define ℕ∞ so that it is the final coalgebra of 1 + (-) using only Book HoTT, deliberately.

But it would be nice to add an "unsafe" module showing that ℕ∞ is equivalent to the well-known type of conatural numbers defined with `codata` or maybe a coinductive record.

Why is this "unsafe"? In particular, nobody discussed or published a model of Book HoTT extended with coinduction.

But, if this TODO is solved, this can be seen as an argument that one could, perhaps, work soundly with the native coinductive definition of ℕ∞, if we wanted to. I say "perhaps" because there are further meta-mathematical issues regarding coinduction in MLTT. I don't regard this problem as solved, not even in the absence of HoTT/UF features.

In any case, this would be something nice to have.

**Comment by martinescardo** [comment]
Solved in #330

**Comment by xekoukou** [comment]
I tend to assume that there exists a final coalgebra of a specific functor, and then in a different file, define a data type conductively and prove that it is a final coalgebra. Thus my assumption is realizable in Agda, which means that I can compile my code.
