### ISSUE TITLE
Should order-theoretic notions be separated out from the Dcpo module?

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#42]
The `Dcpo` module contains the definitions of partial order, meet, join and so on.

https://github.com/martinescardo/TypeTopology/blob/e3835afe052c470bd04333e0e532788441a83720/source/Dcpo.lagda#L37-L53

I am now working on implementing the beginnings of locale theory in `TypeTopology` for which I need these definitions.

Would it be okay to separate these out into a module of their own or was this perhaps deliberately avoided for the sake of self-containment?

**Comment by martinescardo** [comment]
I think this would be OK if @tomdjong agrees.

**Comment by tomdjong** [comment]
@martinescardo Thanks for notifying me. @ayberkt Please go ahead, I would be happy to have them separated.
(I had done this on my clone at some point, but it still needed more refactoring, which I didn't get around to do doing (yet), so this was never merged into TypeTopology.)

**Comment by martinescardo** [comment]
Is this issue resolved?

**Comment by martinescardo** [comment]
Is this issue resolved, @ayberkt ?

**Comment by ayberkt** [comment]
> Is this issue resolved, @ayberkt ?

I think there are no current plans to do this so we can close the issue.

**Comment by ayberkt** [comment]
I‘m re-opening this issue as it has been brought up on Discord by @IanRay11.

**Comment by ayberkt** [comment]
@IanRay11 @tomdjong I believe this has been fixed now that the poset stuff has been moved into the `OrderedTypes` directory, is that correct?

**Comment by IanRay11** [comment]
@ayberkt I'm not sure if I understand the issue from the beginning. But the original reason why I reopened the issue was because my files depend on notions from the Locales folder. At the time it was a bit more developed than the poset file we have in the ordered types folder. If this developed could be copied over to the order theory poset file and I refactor my code to use it then my work would be self contained in this folder. And with that my issue would be closed.

**Comment by tomdjong** [comment]
@ayberkt I think it would be truly fixed if it contained a bit more (e.g. the definition of being an upper bound) and if your files on locale theory used it.
However, Ian's work has been merged and both the domain- and locale-theoretic stuff is working fine right now, so I'm happy to just close this.

**Comment by ayberkt** [comment]
@tomdjong @IanRay11 I see, thanks for the explanation.

Unfortunately, it will be quite time-consuming for me to refactor the locale theory development to work with the definition of poset from the `OrderedTypes` module at the moment. A more feasible alternative could be to factor out the definition of poset that I use in the locale theory development to the `OrderedTypes` directory. This would be a relatively easy change and would at least meet the desideratum of keeping @IanRay11‘s work self-contained.

What parts of the poset machinery in `Locales.Frame` is needed in your work @IanRay11?

**Comment by IanRay11** [comment]
@ayberkt quite a bit actually... if you want to get an idea you can look at the sup lattice and sup lattice small basis files. In fact, these files use some of your sup lattice developments from the locale folder in addition to poset notions.

**Comment by IanRay11** [comment]
> @ayberkt I think it would be truly fixed if it contained a bit more (e.g. the definition of being an upper bound) and if your files on locale theory used it.
> 
> However, Ian's work has been merged and both the domain- and locale-theoretic stuff is working fine right now, so I'm happy to just close this.

Yeah I'm inclined to agree with the above. Type Topology isn't necessarily intended to be as structured as something like the UniMath library so my quarrel is far from priority.

**Comment by tomdjong** [comment]
> A more feasible alternative could be to factor out the definition of poset that I use in the locale theory development to the OrderedTypes directory. This would be a relatively easy change 

Well, keep in mind that the domain theory development then has to be adapted to _your_ definition of poset.

Things work well now, there's no current pressing need to change things and we're both too busy, so I say we keep things as they are and close this issue. We can always revisit it when it naturally comes up.

**Comment by ayberkt** [comment]
> Well, keep in mind that the domain theory development then has to be adapted to your definition of poset.

I wasn’t suggesting to _replace_ the existing definition in `OrderedTypes` with mine (though my previous message wasn’t very clear I guess). I was suggesting to place mine in `OrderedTypes` as an alternative formulation and write down its equivalence with the existing definition. This is a very easy change and it would be better than having my definition in the depths of the `Locales.Frame` module.

> so I say we keep things as they are and close this issue

Agreed, but I would be happy to factor out the definition as I mentioned above if you want.

**Comment by tomdjong** [comment]
@ayberkt Up to you. I don't have strong feelings on this.
