### ISSUE TITLE
Unify two developments of frames (`frame.lagda` and `Frame.lagda`)

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#49]
I just noticed the existence of the module `frame.lagda` which I believe defines σ-frames.

Now that we have `Frame.lagda` (added in #44), we should be a bit careful about the distinction between the two. As of now, the coexistence of multiple definitions that use the same name is a bit confusing.

**Comment by ayberkt** [comment]
> which I believe defines σ-frames

Actually, this seems to define frames in general! Did PR #44 re-define an already existing definition then? What should we do about this?

**Comment by martinescardo** [comment]
I had forgotten that I had already defined frame. I think it is used somewhere, but I only needed a minimal definition of frame (TypeTopology defines things on demand.). We need to check and unify the two separate developments.

**Comment by glangmead** [comment]
This also causes an error on non-case-sensitive systems like macOS with the default filesystem, such that I only obtain one of the two files via git (which is the lowercase frame.lagda): 

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'source/Frame.lagda'
  'source/frame.lagda'
```

**Comment by martinescardo** [comment]
@glangmead: I renamed `frame` to `Frame-version1`. 

@ayberkt: I am going to close this issue. It is actually useful to have the two versions of frames for pedagogical purposes.
