### ISSUE TITLE
∀[ i ∶ I ] e should be ∀ i ∶ I  , e

### ISSUE THREAD

**Issue by martinescardo** [martinescardo/TypeTopology#53]
@ayberkt  we should be consistent and use the same notational conventions as for \Sigma and \exists. So I suggest changing UF-Subsingleton-Combinators.lagda and any module that uses this syntax.

**Comment by ayberkt** [comment]
@martinescardo agreed. I will send a PR that addresses this today.

**Comment by martinescardo** [comment]
There is no hurry.

**Comment by ayberkt** [comment]
@martinescardo

I tried implementing the `∀ i ∶ I , e` syntax but the Agda parser is not happy with it as `∀` is built-in syntax.

How about we use `Ɐ` instead (Unicode `U+2C6F`)?

**Comment by martinescardo** [comment]
Yes, using a different unicode symbol is fine. We can also use a different unicode symbol to denote \exists in this context.
