### ISSUE TITLE
Typechecking workflow fails for no apparent reason

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#54]

**Comment by ayberkt** [comment]
The logs show that running Agda fails with the following error message

```
<stdout>: commitBuffer: invalid argument (invalid character)
```

**Comment by martinescardo** [comment]
Try doing "export LANG=en_GB.UTF-8" before running cabal / stack.

**Comment by martinescardo** [comment]
From here: https://github.com/commercialhaskell/stack/issues/793

**Comment by martinescardo** [comment]
And maybe this: https://github.com/agda/agda/issues/2922

**Comment by ayberkt** [comment]
> Try doing "export LANG=en_GB.UTF-8" before running cabal / stack.

I tried this in #55 and it seems to have fixed it. Merging #55 will close this issue.
