### ISSUE TITLE
Update the typechecking workflow to Agda 2.6.2

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#57]
Now that the new version of Agda has been released, it might be a good idea to update the typechecking workflow to use that.

**Comment by martinescardo** [comment]
TypeTopology works with both 2.6.1 and 2.6.2 currently. So we are ready to move, even if not everybody has switched to 2.6.2. But perhaps we should check with other people?

**Comment by ayberkt** [comment]
> TypeTopology works with both 2.6.1 and 2.6.2 currently. So we are ready to move

Great to hear.

> But perhaps we should check with other people?

Good idea.

**Comment by ayberkt** [comment]
Are we ready to migrate to Agda 2.6.2? Do we still need to check with other people? If we are ready to move, I should take a look at this sometime soon.

**Comment by martinescardo** [comment]
I have been using 2.6.2 for quite a while. So we are ready to migrate to it. But why do we need to if it works with both? This is a genuine question.

**Comment by ayberkt** [comment]
> But why do we need to if it works with both?

I don't think we need to check if it works with both. You mentioned a while ago that we should maybe check with others just in case they are using `TypeTopology` with 2.6.1, but this was a long time ago and I think everyone uses 2.6.2 now so this won't be necessary.
