### ISSUE TITLE
Refactor `InitialFrame` to avoid using full univalence

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#69]
Propositional + functional extensionality should be sufficient as @martinescardo pointed out.

**Comment by ayberkt** [comment]
Use: `propext-funext-give-prop-ua`.

**Comment by martinescardo** [comment]
Any progress with this?

**Comment by ayberkt** [comment]
> Any progress with this?

I'll address is as soon as PR #116 (the universal property of Patch is finalised), which should be soon.

**Comment by ayberkt** [comment]
@martinescardo PR #134 fixes this issue.
