### ISSUE TITLE
Use `꞉` (MODIFIER LETTER COLON) instead of `:` (RATIO) in `UF-Subsingleton-Combinators`

### ISSUE THREAD

**Issue by ayberkt** [martinescardo/TypeTopology#76]
It seems that in

https://github.com/martinescardo/TypeTopology/blob/5f35dfc5a2ce426a13555a26f0f7b83aef5be542/source/UF-Subsingleton-Combinators.lagda#L54-L55

and

https://github.com/martinescardo/TypeTopology/blob/5f35dfc5a2ce426a13555a26f0f7b83aef5be542/source/UF-Subsingleton-Combinators.lagda#L125-L126

I accidentally used the wrong unicode character. I need to fix this at some point.

**Comment by martinescardo** [comment]
Can we close this now?

**Comment by ayberkt** [comment]
> Can we close this now?

No it has still not been fixed. I kept postponing it as this change will have to be propagated in the locale theory library and I wanted to finish the formalisation of Patch first before I do that.
